title : Elementary - Jekyll Blog Theme
name: 'Elementary Jekyll Theme'
description: 'Simple, light weight, responsive jekyll theme for hackers'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  projects:
    title: Projects
    default_open: false
    output: true
  blogs:
    title: Blogs
    default_open: true
    output: true



defaults:
  - scope:
      type: projects
    values:
      title: Projects
      permalink: /project/:title
  - scope:
      type: blogs
    values:
      title: Blogs
      permalink: /blog/:title

plugins:
  - jekyll-sitemap
