title : Aditya Khandkar's blog
name: 'Aditya Khandkar'
description: 'My blog'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

#featured_posts_title: Unrelated
#featured_posts:
#  - url: '#'
#    title: 'Featured post #1'
#  - url: '#'
#    title: 'Featured post #2'
#  - url: '#'
#    title: 'Featured post #3'

collections:
  projects:
    title: Projects
    default_open: true
    output: true
#  blogs:
#    title: Blogs
#    default_open: true
 #   output: true



defaults:
  - scope:
      type: projects
    values:
      title: Projects
      permalink: /project/:title
#  - scope:
#      type: blogs
#    values:
#      title: Blogs
#      permalink: /blog/:title

plugins:
  - jekyll-sitemap
